# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53c51ae26d8e586fab7d2537defdddc401e3142fbdea58f23c33eb8fd44abeb45a37d9130903de01a0a025440e11d5c2491cef6c316e54fcb7a55cf0cbc0e74d

test:
  secret_key_base: 17f9c8113aef02d4a3f625125c49c84648353430540256bb0d81f7fad3ba91c349d0e339272b2fcac82e0e5ec8085d3666fa7dac902cc234af0effb2891362c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
